{{- if and .Values.enabled (not .Values.auth.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyter-training.fullname" . }}-auth
  labels:
    {{- include "jupyter-training.labels" . | nindent 4 }}
    app.kubernetes.io/component: jupyter
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
